# Example configuration entry
esphome:
  name: mediaplayer

esp32:
  board: nodemcu-32s

# Enable logging
logger:

wifi:
  ssid: "FRITZ!Box 7360 SL"
  password: "3226285563773954"

  # Enable fallback hotspot in case WiFi connection fails
  ap:
    ssid: "ESPHome Mediaplayer Fallback Hotspot"
    password: "esphomeHotspot"

ota:
  password: "1234321234543212345654321"

web_server:
  port: 80
  
# Example configuration entry
media_player:
  - platform: i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_lrclk_pin: GPIO33
    i2s_dout_pin: GPIO22
    i2s_bclk_pin: GPIO19
    mode: mono