# Example configuration entry
esphome:
  name: mediaplayer
  
esp32:
  board: nodemcu-32s

# Enable logging
logger:

wifi:
  ssid: "FRITZ!Box 7360 SL"
  password: "3226285563773954"

  # Enable fallback hotspot in case WiFi connection fails
  ap:
    ssid: "ESPHome Fallback Hotspot"
    password: "esphomeHotspot"

web_server:

ota:
  password: "1234321234543212345654321"

# web_server:
#   port: 80

# Example configuration entry
media_player:
  - platform: i2s_audio
    name: ESPHome I2S Media Player
    dac_type: external
    i2s_lrclk_pin: GPIO26
    i2s_dout_pin: GPIO25
    i2s_bclk_pin: GPIO27
    mode: mono

switch:
  - platform: template
    name: switch_web
    id: switch_web
    turn_on_action:
      - media_player.volume_set: 50%
      - media_player.play_media: 'http://live-icy.gss.dr.dk:80/A/A03H.mp3'
    turn_off_action:
      - media_player.stop:
